window.READING_EXPLANATION_FIXES = {
  "101": "Despite her youth = mặc dù tuổi đời còn trẻ\nshe: đại từ chủ ngữ, không đứng trước danh từ\nhers: đại từ sở hữu, không đi với danh từ\nherself: đại từ phản thân, sai cấu trúc\n→ Chọn (B)\nDịch: Mặc dù còn trẻ, cô Cho đã rất nổi tiếng\ntrên mạng xã hội.",
  "102": "be available online = có sẵn trên mạng\nintended: dự định (động từ/tính từ, sai nghĩa)\ncomparable: có thể so sánh (sai nghĩa)\ndecisive: mang tính quyết định (sai ngữ cảnh)\n→ Chọn (A)\nDịch: Hầu hết tài liệu phát tại hội nghị kế toán\ntháng trước hiện đã có sẵn trực tuyến.",
  "103": "conduct a review = tiến hành một cuộc đánh\ngiá\nreviewer: người đánh giá\nreviewed: quá khứ phân từ\nreviews: danh từ số nhiều, không hợp với “a”\n→ Chọn (B)\nDịch: Phòng kế toán sẽ tiến hành một cuộc\nđánh giá toàn diện.",
  "104": "be promoted to president = được thăng chức\nlên\nprovided: cung cấp\ndecorated: trao huân chương\nresponded: phản hồi\n→ Chọn (C)\nDịch: Phó chủ tịch Lucille Jeris đã được thăng\nchức lên chủ tịch công ty.",
  "105": "more productive than = năng suất hơn\nproduction: danh từ\nproductively: trạng từ\nproductivity: danh từ\n→ Chọn (D)\nDịch: Nhân viên nghỉ giải lao thường xuyên làm\nviệc hiệu quả hơn.",
  "106": "contact a technician = liên hệ kỹ thuật viên\nreplacement: sự thay thế\nrenewal: gia hạn\nstructure: cấu trúc\n→ Chọn (B)\nDịch: Khách hàng được khuyến khích liên hệ kỹ\nthuật viên khi máy cần sửa.",
  "107": "nearly caused = suýt nữa gây ra\nnear: tính từ\nnears: động từ\nnearness: danh từ\n→ Chọn (A)\nDịch: Tình trạng kẹt xe nặng suýt khiến cô\nIkeda lỡ chuyến bay.",
  "108": "will probably take place = có khả năng sẽ diễn\nra\noriginally: ban đầu\nregularly: thường xuyên\nthoughtfully: chu đáo\n→ Chọn (B)\nDịch: Nguồn tin cho biết việc sáp nhập có thể\ndiễn ra vào năm tới.",
  "109": "various beautiful rooms = nhiều phòng khác\nnhau\namong: giữa\nthroughout: xuyên suốt\nitself: đại từ phản thân\n→ Chọn (A)\nDịch: Khách sạn Seaborne Inn có nhiều phòng\nđẹp.",
  "110": "located at Gordon Avenue and Hutch Street\n→ at dùng cho vị trí cụ thể\nuntil: cho đến\nagainst: chống lại\naside from: ngoài ra\n→ Chọn (C)\nDịch: Cửa hàng nằm tại đường Gordon và\nHutch.",
  "111": "rated as acceptable = được đánh giá là chấp\nnhận được\nacceptability: danh từ\nacceptance: danh từ\naccepting: V-ing\n→ Chọn (B)\nDịch: Ứng dụng giao thông được đánh giá là\nchấp nhận được.",
  "112": "next weekend → thì hiện tại tiếp diễn chỉ kế\nhoạch\nis representing\nrepresent: hiện tại đơn\ndid represent: quá khứ\nhad represented: quá khứ hoàn thành\n→ Chọn (C)\nDịch: Bác sĩ Cheung sẽ đại diện bệnh viện tại\nhội chợ y tế cuối tuần tới.",
  "113": "financially profitable = có lãi\nplain: bình thường\nfull: đầy\nadditional: thêm\n→ Chọn (B)\nDịch: Cửa hàng có quý kinh doanh sinh lời.",
  "114": "chosen as the supplier = được chọn làm nhà\ncung cấp\nsupply: cung cấp (động từ/danh từ)\nsupplies: số nhiều\nsupplying: V-ing\n→ Chọn (B)\nDịch: Công ty được chọn làm nhà cung cấp\nthiệp.",
  "115": "only organization that tracks = tổ chức duy\nnhất theo dõi\nleadership: sự lãnh đạo\nneighborhood: khu dân cư\nofficial: quan chức\n→ Chọn (D)\nDịch: Đây là tổ chức duy nhất theo dõi quần\nthể hươu.",
  "116": "members who attended = mệnh đề quan hệ\nthey: đại từ\nwhen: trạng từ\nsome: không nối mệnh đề\n→ Chọn (A)\nDịch: Các thành viên đã tham dự được liệt kê\ntrong phụ lục.",
  "117": "specifically designed = được thiết kế một cách\ncụ thể\nspecify: động từ\nspecific: tính từ\nspecificity: danh từ\n→ Chọn (D)\nDịch: Ứng dụng được thiết kế riêng cho giới\nđầu tư.",
  "118": "more people struggle with = nhiều người gặp\nkhó khăn\nstruggles: chia cho số ít\nstruggling: V-ing\nto struggle: nguyên mẫu\n→ Chọn (D)\nDịch: Nhiều người gặp khó khăn khi lái xe ban\nđêm.",
  "119": "in response to = để phản ứng với\neffect: ảnh hưởng\napology: xin lỗi\nconfirmation: xác nhận\n→ Chọn (A)\nDịch: Kế hoạch được lập để phản ứng với việc\ncắt giảm ngân sách.",
  "120": "have consistently been shown = luôn luôn\nđược chứng minh\nemotionally: cảm xúc\ndressed: mặc\nrandomly: ngẫu nhiên\n→ Chọn (A)\nDịch: Tài liệu đào tạo luôn được chứng minh là\nhiệu quả.",
  "121": "former director = cựu giám đốc\nformed: quá khứ\nformalize: động từ\nformality: danh từ\n→ Chọn (B)\nDịch: Bà Yamada, cựu giám đốc, được bổ\nnhiệm.",
  "122": "up to five files = tối đa năm tệp\nfar from: xa\nas for: còn về\nout of: hết\n→ Chọn (C)\nDịch: Có thể mở tối đa năm tệp cùng lúc.",
  "123": "promote activities = quảng bá hoạt động\nrealize: nhận ra\npropose: đề xuất\nobserve: quan sát\n→ Chọn (D)\nDịch: Bản tin giúp quảng bá hoạt động của\nnhóm.",
  "124": "While the hotel does not have… = mặc dù\nSuch as: ví dụ\nUnless: trừ khi\nWithout: không có\n→ Chọn (A)\nDịch: Mặc dù khách sạn không có nhà hàng…",
  "125": "Despite a slight decline = mặc dù có sự sụt\ngiảm\nAside: ngoài ra\nBecoming: V-ing\nOften: trạng từ\n→ Chọn (B)\nDịch: Mặc dù doanh thu giảm nhẹ, công ty vẫn\nmở rộng.",
  "126": "over the past ten years = trong suốt\ninto: vào\nsince: từ (cần mốc)\nbeside: bên cạnh\n→ Chọn (A)\nDịch: Trong suốt 10 năm qua.",
  "127": "holding auditions = tổ chức buổi tuyển vai\nto audition: động từ\nauditioned: quá khứ\naudition: số ít\n→ Chọn (C)\nDịch: Nhà hát đang tổ chức tuyển vai.",
  "128": "packed so hastily = vội vàng\nenormously: rất lớn\nbriefly: ngắn gọn\nmysteriously: bí ẩn\n→ Chọn (C)\nDịch: Ông Kane đóng đồ quá vội.",
  "129": "Long before … → quá khứ hoàn thành\nhad revised\nwas revised: bị động\nis revising: hiện tại\nhas to revise: phải sửa\n→ Chọn (C)\nDịch: Cô Morris đã chỉnh sửa lịch từ rất sớm.",
  "130": "ill return ------- interns have arrived\nnce = ngay khi\nnlike: không giống\nhereas: trong khi\negarding: về việc\nChọn (A)\nịch: Ông Swan sẽ quay lại khi thực tập sinh\nã đến.\nạn!\ntận tháng Giêng, và chúng tôi sẽ tặng\ntừ 50 đô la trở lên. Ngoài ra, tiền thưởng\nmột tài khoản tiết kiệm Avanti riêng biệt\ng trình nhân đôi phần thưởng trên ứng\nively), hãy ghé qua chi nhánh của Avanti để\ni phần thưởng kết thúc vào ngày 31\nJanuary 31). Vào ngày 1 tháng 2, phần\n0 đô la.",
  "131": "Đáp án (A) purchase. Sau “every” cần một danh từ đếm được số ít. “purchase” nghĩa là một lần mua/giao dịch, phù hợp với cụm “every purchase of $50 or more”.",
  "132": "Đáp án (D) automatically. Chỗ trống bổ nghĩa cho động từ “deposited”, vì vậy cần trạng từ. “automatically deposited” = được tự động gửi vào tài khoản.",
  "133": "Đáp án (A) Alternatively. Câu trước hướng dẫn đăng ký trên ứng dụng; câu sau đưa ra một lựa chọn khác là đến chi nhánh Avanti để được hỗ trợ. “Alternatively” diễn đạt đúng quan hệ lựa chọn thay thế.",
  "134": "Đáp án (B) Don’t wait—the double-rewards promotion ends on January 31. Câu sau nói từ ngày 1 tháng 2 mức hoàn tiền trở lại $2, nên câu phù hợp phải cho biết chương trình thưởng gấp đôi kết thúc ngày 31 tháng 1.",
  "135": "Đáp án (B) Instead. Winnie không rời công ty; thay vào đó, cô ấy sẽ đảm nhiệm vị trí regional distribution manager. “Instead” thể hiện sự chuyển hướng tương phản này.",
  "136": "Đáp án (B) promotion. Việc chuyển từ team captain lên regional distribution manager là một sự thăng chức. Cụm “thrilled about her promotion” phù hợp cả nghĩa và ngữ pháp.",
  "137": "Đáp án (A) final. Chỗ trống đứng trước danh từ “day”, nên cần tính từ. “her final day with us” = ngày cuối cùng cô ấy làm việc cùng nhóm hiện tại.",
  "138": "Đáp án (C) Please join us for coffee and cake. Đoạn văn đang mời nhân viên đến dự tiệc chia tay Winnie lúc 3:00 P.M.; lời mời dùng coffee and cake nối tiếp tự nhiên nhất.",
  "139": "Đáp án (B) Reveal your company’s greatest strength from the outset. Câu trước khuyên không để nhà đầu tư phải chờ đợi; câu sau nói cách này giúp thu hút sự chú ý. Vì vậy cần nêu điểm mạnh nhất ngay từ đầu.",
  "140": "Đáp án (D) relevant. Cấu trúc “be relevant to” nghĩa là có liên quan đến. Kinh nghiệm của nhóm cần có liên quan đến sản phẩm hoặc dịch vụ mà công ty cung cấp.",
  "141": "Đáp án (C) what. Mệnh đề “what sets your company apart” đóng vai trò chủ ngữ của “is its unique vision”. “What” mang nghĩa “điều khiến công ty khác biệt”.",
  "142": "Đáp án (A) funding. Bài viết nói về thuyết trình trước nhà đầu tư; nếu thuyết phục được họ, công ty có khả năng nhận được nguồn vốn mà mình tìm kiếm.",
  "143": "Đáp án (B) system. “Online payroll portal” là một hệ thống trực tuyến; trong thời gian nâng cấp, nhân viên được yêu cầu không truy cập hệ thống đó.",
  "144": "Đáp án (C) will enable. Đoạn văn mô tả chức năng của trang web sau khi nâng cấp, nên dùng tương lai đơn: “The updated site will enable users to…”.",
  "145": "Đáp án (D) This function will optimize the services offered by the department. Câu ngay trước giới thiệu chức năng live chat với bộ phận nhân sự; “This function” liên kết trực tiếp với chức năng đó và nêu lợi ích của nó.",
  "146": "Đáp án (C) during. Cụm “during the period mentioned above” nghĩa là trong khoảng thời gian đã nêu (8–12 April), phù hợp với ngữ cảnh cần truy cập thông tin khi hệ thống ngừng hoạt động.",
  "147": "Đáp án (D) A car wash. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "148": "Đáp án (C) It must be used before the end of August.. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "149": "Đáp án (B) To publicize the start of a renovation project. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "150": "Đáp án (D) Artists will deliver wall decoration ideas. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "151": "Đáp án (C) To invite Mr. Sanchez to an event. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "152": "Đáp án (D) He has a membership at an art museum.. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "153": "Đáp án (A) Renting a temporary space. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "154": "Đáp án (C) He is willing to drive a van to a location.. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "155": "Đáp án (A) A maker of computer furniture. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "156": "Đáp án (D) Read product reviews. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "157": "Đáp án (C) To obtain a price quote for a large order. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "158": "Đáp án (C) She congratulated staff on the latest sales figures.. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "159": "Đáp án (D) Mr. Sung. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "160": "Đáp án (A) A colleague is planning to move there.. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "161": "Đáp án (B) He conducts research at an institution.. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "162": "Đáp án (D) Collaborate with Dr. Able’s team. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "163": "Đáp án (B) [2]. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "164": "Đáp án (A) It is a remote position.. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "165": "Đáp án (C) Good communication skills. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "166": "Đáp án (C) The starting date. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "167": "Đáp án (A) [1]. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "168": "Đáp án (C) It offers nature-related courses.. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "169": "Đáp án (D) To attract a wide variety of birds. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "170": "Đáp án (C) University professors. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "171": "Đáp án (D) Preparing the ground for planting. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "172": "Đáp án (A) Increase her team’s marketing budget. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "173": "Đáp án (D) It does not sell well at a certain time of year.. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "174": "Đáp án (B) He can fulfill Ms. Parkin’s request.. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "175": "Đáp án (D) Social media. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "176": "Đáp án (C) It makes its products with locally sourced parts.. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "177": "Đáp án (B) Post photos online. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "178": "Đáp án (A) By talking to a colleague at work. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "179": "Đáp án (D) He received his order sooner than he expected.. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "180": "Đáp án (B) satisfy. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "181": "Đáp án (B) To profile a successful local business. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "182": "Đáp án (C) He created a company 100 years ago.. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "183": "Đáp án (B) She wants to return to Edinburgh.. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "184": "Đáp án (A) values. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "185": "Đáp án (D) She had a good experience with a product from Milne Associates.. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "186": "Đáp án (A) A farmer. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "187": "Đáp án (B) They are too fragile.. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "188": "Đáp án (C) It seats no more than 75 people.. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "189": "Đáp án (D) Collaborate on research projects. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "190": "Đáp án (C) They are more than 800 years old.. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "191": "Đáp án (B) On Wednesday. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "192": "Đáp án (D) An executive assistant. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "193": "Đáp án (A) The results of some interviews. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "194": "Đáp án (B) Technology updates. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "195": "Đáp án (B) Attempt to contact some marketing team members. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "196": "Đáp án (A) He is originally from Gradey City.. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "197": "Đáp án (B) Hiring singers at short notice. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "198": "Đáp án (C) He paid MLP a €300 fee.. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "199": "Đáp án (D) On August 11. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu.",
  "200": "Đáp án (D) Visit the Resources page to upload a video recording. Lựa chọn này phù hợp với thông tin và ngữ cảnh của bài đọc; các phương án còn lại không khớp với chi tiết được nêu trong tài liệu."
};
